apiServer:
  extraArgs:
  - name: authorization-mode
    value: Node,RBAC
  - name: client-ca-file
    value: /etc/kubernetes/pki/ca.crt
  - name: default-not-ready-toleration-seconds
    value: "45"
  - name: default-unreachable-toleration-seconds
    value: "45"
  - name: enable-aggregator-routing
    value: "true"
  - name: enable-bootstrap-token-auth
    value: "true"
  - name: etcd-cafile
    value: /etc/kubernetes/pki/etcd/ca.crt
  - name: etcd-certfile
    value: /etc/kubernetes/pki/etcd/server.crt
  - name: etcd-keyfile
    value: /etc/kubernetes/pki/etcd/server.key
  - name: kubelet-client-certificate
    value: /etc/kubernetes/pki/apiserver-kubelet-client.crt
  - name: kubelet-client-key
    value: /etc/kubernetes/pki/apiserver-kubelet-client.key
  - name: kubelet-preferred-address-types
    value: InternalIP,ExternalIP,Hostname,InternalDNS,ExternalDNS
  - name: profiling
    value: "false"
  - name: proxy-client-cert-file
    value: /etc/kubernetes/pki/front-proxy-client.crt
  - name: proxy-client-key-file
    value: /etc/kubernetes/pki/front-proxy-client.key
  - name: requestheader-allowed-names
    value: front-proxy-client
  - name: requestheader-client-ca-file
    value: /etc/kubernetes/pki/front-proxy-ca.crt
  - name: requestheader-extra-headers-prefix
    value: X-Remote-Extra-
  - name: requestheader-group-headers
    value: X-Remote-Group
  - name: requestheader-username-headers
    value: X-Remote-User
  - name: service-account-key-file
    value: /etc/kubernetes/pki/sa.pub
  - name: service-account-lookup
    value: "true"
  - name: tls-cert-file
    value: /etc/kubernetes/pki/apiserver.crt
  - name: tls-cipher-suites
    value: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256
  - name: tls-private-key-file
    value: /etc/kubernetes/pki/apiserver.key
apiVersion: kubeadm.k8s.io/v1beta4
caCertificateValidityPeriod: 87600h0m0s
certificatesDir: /etc/kubernetes/pki
clusterName: my-cluster
controlPlaneEndpoint: REPLACE_ME:6443
controllerManager:
  extraArgs:
  - name: allocate-node-cidrs
    value: "true"
  - name: authentication-kubeconfig
    value: /etc/kubernetes/controller-manager.conf
  - name: authorization-kubeconfig
    value: /etc/kubernetes/controller-manager.conf
  - name: bind-address
    value: 0.0.0.0
  - name: cluster-signing-cert-file
    value: /etc/kubernetes/pki/ca.crt
  - name: cluster-signing-duration
    value: 6h0m0s
  - name: cluster-signing-key-file
    value: /etc/kubernetes/pki/ca.key
  - name: kubeconfig
    value: /etc/kubernetes/controller-manager.conf
  - name: profiling
    value: "false"
  - name: requestheader-client-ca-file
    value: /etc/kubernetes/pki/front-proxy-ca.crt
  - name: root-ca-file
    value: /etc/kubernetes/pki/ca.crt
  - name: secure-port
    value: "10257"
  - name: service-account-private-key-file
    value: /etc/kubernetes/pki/sa.key
  - name: terminated-pod-gc-threshold
    value: "10"
  - name: use-service-account-credentials
    value: "true"
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
    extraArgs:
    - name: auto-tls
      value: "false"
    - name: cert-file
      value: /etc/kubernetes/pki/etcd/server.crt
    - name: cipher-suites
      value: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256
    - name: client-cert-auth
      value: "true"
    - name: key-file
      value: /etc/kubernetes/pki/etcd/server.key
    - name: peer-auto-tls
      value: "false"
    - name: peer-client-cert-auth
      value: "true"
    - name: trusted-ca-file
      value: /etc/kubernetes/pki/etcd/ca.crt
featureGates:
  ControlPlaneKubeletLocalMode: true
imageRepository: registry.k8s.io
kind: ClusterConfiguration
kubernetesVersion: v1.36.1
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
proxy: {}
scheduler:
  extraArgs:
  - name: bind-address
    value: 0.0.0.0
  - name: kubeconfig
    value: /etc/kubernetes/scheduler.conf
  - name: profiling
    value: "false"
  - name: secure-port
    value: "10259"
