apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argocd-repo-server-pvc
  namespace: argocd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: hcloud-volumes
