apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argocd-app-controller-pvc
  namespace: argocd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: hcloud-volumes
